#include "Instructions.h"

#define NO_OPERANDS {OPERAND_TYPE_NO_OPERANDS, OPERAND_TYPE_NO_OPERANDS, OPERAND_TYPE_NO_OPERANDS, OPERAND_TYPE_NO_OPERANDS}
#define _1_OPERANDS(op1) {op1, OPERAND_TYPE_NO_OPERANDS, OPERAND_TYPE_NO_OPERANDS, OPERAND_TYPE_NO_OPERANDS}
#define _2_OPERANDS(op1, op2) {op1, op2, OPERAND_TYPE_NO_OPERANDS, OPERAND_TYPE_NO_OPERANDS}
#define _3_OPERANDS(op1, op2, op3) {op1, op2, op3, OPERAND_TYPE_NO_OPERANDS}
#define _4_OPERANDS(op1, op2, op3, op4) {op1, op2, op3, op4}


InstructionOperand instructionOperands[] = {
//UNKNOWN INSTRUCTION
NO_OPERANDS,

//AAA
NO_OPERANDS,

//AAD
_1_OPERANDS(OPERAND_TYPE_IMM8),

//AAM
_1_OPERANDS(OPERAND_TYPE_IMM8),

//AAS
NO_OPERANDS,

//ADC
_2_OPERANDS(OPERAND_TYPE_IMPLICIT_AL, OPERAND_TYPE_IMM8),
_2_OPERANDS(OPERAND_TYPE_IMPLICIT_AX_EAX_RAX, OPERAND_TYPE_IMM16_32),
_2_OPERANDS(OPERAND_TYPE_RM8, OPERAND_TYPE_IMM8),
_2_OPERANDS(OPERAND_TYPE_RM16_32_64, OPERAND_TYPE_IMM16_32),
_2_OPERANDS(OPERAND_TYPE_RM16_32_64, OPERAND_TYPE_IMM8),
_2_OPERANDS(OPERAND_TYPE_RM8, OPERAND_TYPE_R8),
_2_OPERANDS(OPERAND_TYPE_RM16_32_64, OPERAND_TYPE_R16_32_64),
_2_OPERANDS(OPERAND_TYPE_R8, OPERAND_TYPE_RM8),
_2_OPERANDS(OPERAND_TYPE_R16_32_64, OPERAND_TYPE_RM16_32_64),

//ADCX
_2_OPERANDS(OPERAND_TYPE_R32_64, OPERAND_TYPE_RM32_64),

//ADD
_2_OPERANDS(OPERAND_TYPE_IMPLICIT_AL, OPERAND_TYPE_IMM8),
_2_OPERANDS(OPERAND_TYPE_IMPLICIT_AX_EAX_RAX, OPERAND_TYPE_IMPLICIT_AX_EAX_RAX),
_2_OPERANDS(OPERAND_TYPE_RM8, OPERAND_TYPE_IMM8),
_2_OPERANDS(OPERAND_TYPE_RM16_32_64, OPERAND_TYPE_IMM16_32),
_2_OPERANDS(OPERAND_TYPE_RM16_32_64, OPERAND_TYPE_IMM8),
_2_OPERANDS(OPERAND_TYPE_RM8, OPERAND_TYPE_R8),
_2_OPERANDS(OPERAND_TYPE_RM16_32_64, OPERAND_TYPE_R16_32_64),
_2_OPERANDS(OPERAND_TYPE_R8, OPERAND_TYPE_RM8),
_2_OPERANDS(OPERAND_TYPE_R16_32_64, OPERAND_TYPE_RM16_32_64),
};