#include "Instructions.h"

instructionOperandEncoding_t instructionOperandEncoding[] = {
	//UNKNOWN INSTRUCTION
	INSTRUCTION_OPERAND_ENCODING_NA,

	//AAA
	INSTRUCTION_OPERAND_ENCODING_NA,

	//AAD
	INSTRUCTION_OPERAND_ENCODING_IMM,

	//AAM
	INSTRUCTION_OPERAND_ENCODING_IMM,

	//AAs
	INSTRUCTION_OPERAND_ENCODING_NA,

	//ADC
	INSTRUCTION_OPERAND_ENCODING_IMPLIED_AX_IMM,
	INSTRUCTION_OPERAND_ENCODING_IMPLIED_AX_IMM,
	INSTRUCTION_OPERAND_ENCODING_RM_IMM,
	INSTRUCTION_OPERAND_ENCODING_RM_IMM,
	INSTRUCTION_OPERAND_ENCODING_RM_IMM,
	INSTRUCTION_OPERAND_ENCODING_RM_R,
	INSTRUCTION_OPERAND_ENCODING_RM_R,
	INSTRUCTION_OPERAND_ENCODING_R_RM,
	INSTRUCTION_OPERAND_ENCODING_R_RM,

	//ADCX
	INSTRUCTION_OPERAND_ENCODING_R_RM,

	//ADD
	INSTRUCTION_OPERAND_ENCODING_IMPLIED_AX_IMM,
	INSTRUCTION_OPERAND_ENCODING_IMPLIED_AX_IMM,
	INSTRUCTION_OPERAND_ENCODING_RM_IMM,
	INSTRUCTION_OPERAND_ENCODING_RM_IMM,
	INSTRUCTION_OPERAND_ENCODING_RM_IMM,
	INSTRUCTION_OPERAND_ENCODING_RM_R,
	INSTRUCTION_OPERAND_ENCODING_RM_R,
	INSTRUCTION_OPERAND_ENCODING_R_RM,
	INSTRUCTION_OPERAND_ENCODING_R_RM,

	//
};