#include "Instructions.h"

#define INSTRUCTION(name, op) {name, PREFIX_CONTEXT_PREFIX_NOT_REQUIRED, op, INSTRUCTION_ENVIRONMENT_NO_ENVIRONMENT}
#define INSTRUCTION_P(name, prefix, op) {name, prefix, op, INSTRUCTION_ENVIRONMENT_NO_ENVIRONMENT}
#define INSTRUCTION_PE(name, prefix, op, env) {name, prefix, op, env}
#define INSTRUCTION_E(name, op, env) {name, PREFIX_CONTEXT_PREFIX_NOT_REQUIRED, op, env}

InstructionInfo instructionList[] = {
//UNKNOWN INSTRUCTION
INSTRUCTION(0, 0x0),

//AAA
INSTRUCTION(1, 0x37),

//AAD
INSTRUCTION(2, 0xD5),

//AAM
INSTRUCTION(3, 0xD4),

//AAS
INSTRUCTION(4, 0x3F),

//ADC
INSTRUCTION(5, 0x14),
INSTRUCTION(5, 0x15),
INSTRUCTION_E(5, 0x80, INSTRUCTION_ENVIRONMENT_MODRM_REG_2),
INSTRUCTION_E(5, 0x81, INSTRUCTION_ENVIRONMENT_MODRM_REG_2),
INSTRUCTION_E(5, 0x83, INSTRUCTION_ENVIRONMENT_MODRM_REG_2),
INSTRUCTION(5, 0x10),
INSTRUCTION(5, 0x11),
INSTRUCTION(5, 0x12),
INSTRUCTION(5, 0x13),

//ADCX
INSTRUCTION_PE(6, PREFIX_CONTEXT_PREFIX_66, 0x0F38F6, INSTRUCTION_ENVIRONMENT_REQUIRES_PREFIX_66),

//ADD
INSTRUCTION(7, 0x04),
INSTRUCTION(7, 0x05),
INSTRUCTION_E(7, 0x80, INSTRUCTION_ENVIRONMENT_MODRM_REG_0),
INSTRUCTION_E(7, 0x81, INSTRUCTION_ENVIRONMENT_MODRM_REG_0),
INSTRUCTION_E(7, 0x83, INSTRUCTION_ENVIRONMENT_MODRM_REG_0),
INSTRUCTION(7, 0x00),
INSTRUCTION(7, 0x01),
INSTRUCTION(7, 0x02),
INSTRUCTION(7, 0x03),


};


//uint64_t instructionListLength = 15;
uint64_t instructionListLength = COUNT_OF(instructionList);