#include "Instructions.h"

instructionOperandEncoding_t instructionOperandEncoding[] = {
	//UNKNOWN INSTRUCTION
	INSTRUCTION_OPERAND_ENCODING_NA,

	//AAA
	INSTRUCTION_OPERAND_ENCODING_NA,

	//AAD
	INSTRUCTION_OPERAND_ENCODING_IMM,

	//AAM
	INSTRUCTION_OPERAND_ENCODING_IMM,

	//AAs
	INSTRUCTION_OPERAND_ENCODING_NA,

	//ADC
	INSTRUCTION_OPERAND_ENCODING_IMPLIED_AX_IMM,
	INSTRUCTION_OPERAND_ENCODING_IMPLIED_AX_IMM,
	INSTRUCTION_OPERAND_ENCODING_RM_IMM,
	INSTRUCTION_OPERAND_ENCODING_RM_IMM,
	INSTRUCTION_OPERAND_ENCODING_RM_IMM,
	INSTRUCTION_OPERAND_ENCODING_RM_R,
	INSTRUCTION_OPERAND_ENCODING_RM_R,
	INSTRUCTION_OPERAND_ENCODING_R_RM,
	INSTRUCTION_OPERAND_ENCODING_R_RM,

	//ADCX
	INSTRUCTION_OPERAND_ENCODING_R_RM,

	//ADD
	INSTRUCTION_OPERAND_ENCODING_IMPLIED_AX_IMM,
	INSTRUCTION_OPERAND_ENCODING_IMPLIED_AX_IMM,
	INSTRUCTION_OPERAND_ENCODING_RM_IMM,
	INSTRUCTION_OPERAND_ENCODING_RM_IMM,
	INSTRUCTION_OPERAND_ENCODING_RM_IMM,
	INSTRUCTION_OPERAND_ENCODING_RM_R,
	INSTRUCTION_OPERAND_ENCODING_RM_R,
	INSTRUCTION_OPERAND_ENCODING_R_RM,
	INSTRUCTION_OPERAND_ENCODING_R_RM,

	//ADDPD
	INSTRUCTION_OPERAND_ENCODING_R_RM,
	INSTRUCTION_OPERAND_ENCODING_R_VEC_RM,
	INSTRUCTION_OPERAND_ENCODING_R_VEC_RM,

	//ADDPS
	INSTRUCTION_OPERAND_ENCODING_R_RM,
	INSTRUCTION_OPERAND_ENCODING_R_VEC_RM,
	INSTRUCTION_OPERAND_ENCODING_R_VEC_RM,

	//ADDSD
	INSTRUCTION_OPERAND_ENCODING_R_RM,
	INSTRUCTION_OPERAND_ENCODING_R_VEC_RM,
	INSTRUCTION_OPERAND_ENCODING_R_VEC_RM,

	//ADDSS
INSTRUCTION_OPERAND_ENCODING_R_RM,
INSTRUCTION_OPERAND_ENCODING_R_VEC_RM,
INSTRUCTION_OPERAND_ENCODING_R_VEC_RM,

//ADDSUBPD
INSTRUCTION_OPERAND_ENCODING_R_RM,
INSTRUCTION_OPERAND_ENCODING_R_VEC_RM,

//ADDSUBPS
INSTRUCTION_OPERAND_ENCODING_R_RM,
INSTRUCTION_OPERAND_ENCODING_R_VEC_RM,

//ADOX
INSTRUCTION_OPERAND_ENCODING_R_RM,

//AESDEC
INSTRUCTION_OPERAND_ENCODING_R_RM,
INSTRUCTION_OPERAND_ENCODING_R_VEC_RM,

//AESDECLAST
INSTRUCTION_OPERAND_ENCODING_R_RM,
INSTRUCTION_OPERAND_ENCODING_R_VEC_RM,

//AESENC
INSTRUCTION_OPERAND_ENCODING_R_RM,
INSTRUCTION_OPERAND_ENCODING_R_VEC_RM,

//AESENCLAST
INSTRUCTION_OPERAND_ENCODING_R_RM,
INSTRUCTION_OPERAND_ENCODING_R_VEC_RM,

//AESIMC
INSTRUCTION_OPERAND_ENCODING_R_RM,
INSTRUCTION_OPERAND_ENCODING_R_RM,

//AESKEYGENASSIST
INSTRUCTION_OPERAND_ENCODING_R_RM_IMM,
INSTRUCTION_OPERAND_ENCODING_R_RM_IMM,

//AND
INSTRUCTION_OPERAND_ENCODING_IMM,
INSTRUCTION_OPERAND_ENCODING_IMM,
INSTRUCTION_OPERAND_ENCODING_RM_IMM,
INSTRUCTION_OPERAND_ENCODING_RM_IMM,
INSTRUCTION_OPERAND_ENCODING_RM_IMM,
INSTRUCTION_OPERAND_ENCODING_RM_R,
INSTRUCTION_OPERAND_ENCODING_RM_R,
INSTRUCTION_OPERAND_ENCODING_R_RM,
INSTRUCTION_OPERAND_ENCODING_R_RM,
};